### ISSUE TITLE
Todo / known issues

### ISSUE THREAD

**Issue by micuat** [micuat/Pathfinder#1]
- [ ] borderless screen with PSurfaceAWT
  - use fullscreen mode at the moment
- [ ] GUI loop / manual freeze
- [ ] GUI sequence not interactive
- [ ] GUI add/remove sequence
- [ ] GUI RangeY == 1 crashes
